language: erlang
sudo: false
notifications: {email: {on_success: never}}
before_script: set -e
after_script: set +e
after_install: emacs --version
script: make test all
addons:
  apt:
    sources:
    - sourceline: ppa:cassou/emacs
    packages:
    - emacs
