language: bash
sudo: false
before_script: set -e
after_script: set +e
addons:
  apt:
    sources:
      - sourceline: ppa:cassou/emacs
    packages:
      - emacs
after_install: emacs --version
script:
  - make test
  - shellcheck *.sh
  - make
  - git --no-pager diff
  - '[[ 0 -eq $(git --no-pager diff --name-only | wc -l) ]]'
notifications:
  email:
    on_success: never
