on: [push]
name: ci
defaults:
  run:
    shell: bash
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get update
    - run: sudo apt-get install -y --no-install-recommends emacs-nox
    - run: emacs --version
    - run: sudo apt-get install -y --no-install-recommends erlang rebar3
    - run: erl -eval '{ok, Version} = file:read_file(filename:join([code:root_dir(), "releases", erlang:system_info(otp_release), "OTP_VERSION"])), io:fwrite(Version), halt().' -noshell
    - run: rebar3 version
    - uses: actions/checkout@v3
    - run: make test all
    - run: git --no-pager diff --exit-code
