on: [push]
name: ci
jobs:

  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ludeeus/action-shellcheck@2.0.0
      with:
        check_together: 'yes'

  ci:
    runs-on: ubuntu-latest
    container:
      image: docker.io/library/erlang:25@sha256:e0c6f63b49fef9c9d76e8d0c53d59b5edb0af4e72080276009fd170a1f8cad5b
    steps:
    - uses: actions/checkout@v3
    - run: emacs --version
    - run: make test all
    - run: git --no-pager diff --exit-code
