on:
  push:
    tags: ['*']

jobs:
  publish:
    name: Publish ${{ github.ref }} to Hex
    runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v3
  - uses: erlangpack/github-action@v3
    env:
      HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
